site_name: PIA - Curso de Especialización
site_url: https://rafasalaesteve.github.io/PIA
use_directory_urls: true
repo_url: https://github.com/RafaSalaEsteve/PIA
repo_name: RafaSalaEsteve/PIA

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  language: es
  features:
    - navigation.tabs
    - navigation.top
    - palette.toggle
    - content.code.copy
    - content.code.annotate

  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro

    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro


    

nav:
  - Inicio: index.md
  - Guía: guia.md
  - Unitat 1. Introducció a la Programació:
      - 1. Algorismes i llenguatges: Unitat_1.Introduccio_a_la_Programacio/teoria1_algorismes_i_llenguatges.md
      - 2. Exercici pràctic: Unitat_1.Introduccio_a_la_Programacio/exercicis.md


markdown_extensions:
  - admonition
  - footnotes
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets:
      base_path: !relative  # rutas relativas al archivo Markdown actual


plugins:
  - search
  - git-revision-date-localized
  - minify:
      minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RafaSalaEsteve/PIA
  logo: images/logo.png
  favicon: images/favicon.ico
