site_name: PIA - Curso de Especialización
site_url: https://rafasalaesteve.github.io/PIA
use_directory_urls: true
repo_url: https://github.com/RafaSalaEsteve/PIA
repo_name: RafaSalaEsteve/PIA

theme:
  name: material
  language: es
  features:
    - navigation.tabs
    - navigation.top
    - palette.toggle

  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro

    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro


    

nav:
  - Inicio: index.md
  - Guía: guia.md
  - Recursos: recursos.md

markdown_extensions:
  - admonition
  - footnotes
  - codehilite
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - git-revision-date-localized
  - minify:
      minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RafaSalaEsteve/PIA
  logo: images/logo.png
  favicon: images/favicon.ico
